In [10]:
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


- Quadratic Probing (Thăm dò Quadratic) : Ra đời để giải quyết hiện tượng "clustering" trong phương pháp Linear Probing. Ý tưởng là : Thay vì cứ kiểm tra lần lượt từng ô (bắt đầu từ ô hash(x)) thì ta sẽ kiểm tra một cách ngắt quãng tức theo công thức i * i (là kiểm tra tại các ô hash(x), rồi hash(x) + 1 /* 1, rồi hash(x) + 2 /* 2,... cứ như vậy có tới khi tìm thấy ô trống để có thể điền key mới vào)